export type CatalogProduct = {
  slug: string;
  name: string;
  category: string;
  type: string;
  tag: string;
  price: string;
  description: string;
  meter: string;
  specs: string[];
};

export const catalogProducts: CatalogProduct[] = [
  {
    slug: "specter-8k-mouse",
    name: "Specter 8K Mouse",
    category: "Mice",
    type: "Wireless",
    tag: "Best Seller",
    price: "$79",
    description: "Ultra-light shell, 8K polling, and magnetic side grips for ranked play.",
    meter: "89%",
    specs: ["8K polling", "Ultra-light shell", "Magnetic side grips", "PTFE skates"],
  },
  {
    slug: "cipher-mini-mouse",
    name: "Cipher Mini Mouse",
    category: "Mice",
    type: "Claw Grip",
    tag: "New",
    price: "$69",
    description: "Compact shell with optical switches and low-friction skates for fast flicks.",
    meter: "77%",
    specs: ["Compact body", "Optical switches", "Low-friction feet", "Low-click latency"],
  },
  {
    slug: "axiom-ergo-mouse",
    name: "Axiom Ergo Mouse",
    category: "Mice",
    type: "Ergonomic",
    tag: "Work + Play",
    price: "$89",
    description: "Split-angle ergonomic form with programmable side dial and silent clicks.",
    meter: "71%",
    specs: ["Split-angle frame", "Programmable side dial", "Silent switches", "Bluetooth + 2.4G"],
  },
  {
    slug: "vector-75-keyboard",
    name: "Vector 75 Keyboard",
    category: "Keyboards",
    type: "75%",
    tag: "Drop 03",
    price: "$149",
    description: "Hot-swappable 75% board with gasket mount and low-latency wireless mode.",
    meter: "72%",
    specs: ["75% layout", "Hot-swappable sockets", "Gasket mount", "Low-latency mode"],
  },
  {
    slug: "nova-tkl-keyboard",
    name: "Nova TKL Keyboard",
    category: "Keyboards",
    type: "TKL",
    tag: "Tournament",
    price: "$129",
    description: "Tenkeyless aluminum board tuned for rapid actuation and stable key feel.",
    meter: "68%",
    specs: ["TKL layout", "Aluminum frame", "Rapid actuation", "South-facing RGB"],
  },
  {
    slug: "pulse-60-keyboard",
    name: "Pulse 60 Keyboard",
    category: "Keyboards",
    type: "60%",
    tag: "Compact",
    price: "$119",
    description: "Portable 60% layout with per-key RGB and triple-device Bluetooth pairing.",
    meter: "64%",
    specs: ["60% compact", "Per-key RGB", "Triple BT pairing", "Programmable layers"],
  },
  {
    slug: "ghostloop-earbuds",
    name: "GhostLoop Earbuds",
    category: "Audio",
    type: "Earbuds",
    tag: "New",
    price: "$109",
    description: "Gaming-tuned ANC earbuds with 35-hour battery and dual device pairing.",
    meter: "64%",
    specs: ["ANC", "35-hour battery", "Dual device pairing", "Low-latency mode"],
  },
  {
    slug: "echoframe-headset",
    name: "EchoFrame Headset",
    category: "Audio",
    type: "Headset",
    tag: "Spatial",
    price: "$139",
    description: "Closed-back headset with detachable boom mic and low-latency 2.4G dongle.",
    meter: "73%",
    specs: ["Closed-back", "Detachable mic", "2.4G dongle", "Spatial sound"],
  },
  {
    slug: "vibemic-usb",
    name: "VibeMic USB",
    category: "Audio",
    type: "Microphone",
    tag: "Creator",
    price: "$99",
    description: "USB-C condenser mic with tap mute, gain dial, and cardioid recording mode.",
    meter: "69%",
    specs: ["USB-C", "Tap mute", "Gain dial", "Cardioid mode"],
  },
  {
    slug: "fluxdock-7-in-1",
    name: "FluxDock 7-in-1",
    category: "Power + Docks",
    type: "Dock",
    tag: "Creator Pick",
    price: "$89",
    description: "USB-C dock with HDMI 4K60, ethernet, PD passthrough, and SD transfer.",
    meter: "81%",
    specs: ["HDMI 4K60", "Gigabit ethernet", "PD passthrough", "SD transfer"],
  },
  {
    slug: "voltcore-20k",
    name: "VoltCore 20K",
    category: "Power + Docks",
    type: "Power Bank",
    tag: "Fast Charge",
    price: "$74",
    description: "20,000mAh battery with dual USB-C PD outputs and onboard power display.",
    meter: "75%",
    specs: ["20,000mAh", "Dual USB-C PD", "Power display", "Fast recharge"],
  },
  {
    slug: "arccharge-gan-120w",
    name: "ArcCharge GaN 120W",
    category: "Power + Docks",
    type: "Wall Charger",
    tag: "GaN",
    price: "$65",
    description: "Compact multi-port GaN charger for laptop, tablet, and phone fast charging.",
    meter: "80%",
    specs: ["120W GaN", "Multi-port", "Thermal protection", "Travel friendly"],
  },
  {
    slug: "glide-xl-mousepad",
    name: "Glide XL Mousepad",
    category: "Mousepads",
    type: "Control",
    tag: "Desk Mat",
    price: "$35",
    description: "Extended control surface with stitched edges and anti-slip natural rubber base.",
    meter: "66%",
    specs: ["Extended size", "Control weave", "Stitched edges", "Anti-slip base"],
  },
  {
    slug: "slipstream-speedpad",
    name: "Slipstream Speedpad",
    category: "Mousepads",
    type: "Speed",
    tag: "Esports",
    price: "$39",
    description: "Low-friction speed surface tuned for low-DPI tracking and rapid flick shots.",
    meter: "63%",
    specs: ["Speed weave", "Low friction", "Esports tuned", "Stable tracking"],
  },
  {
    slug: "orbit-cam-4k",
    name: "Orbit Cam 4K",
    category: "Streaming",
    type: "Webcam",
    tag: "Streaming",
    price: "$119",
    description: "4K webcam with auto-light correction and magnetic privacy cover.",
    meter: "70%",
    specs: ["4K sensor", "Auto-light correction", "Magnetic cover", "Plug-and-play"],
  },
  {
    slug: "beam-key-light",
    name: "Beam Key Light",
    category: "Streaming",
    type: "Lighting",
    tag: "Studio",
    price: "$89",
    description: "Edge-lit key light with app presets for warm, neutral, and cool scenes.",
    meter: "67%",
    specs: ["Edge-lit diffusion", "App presets", "Warm to cool range", "Desk clamp"],
  },
];

export const getProductBySlug = (slug: string) => {
  return catalogProducts.find((item) => item.slug === slug);
};
