export type CatalogProduct = {
  slug: string;
  name: string;
  category: string;
  type: string;
  tag: string;
  price: string;
  description: string;
  meter: string;
  specs: string[];
  image?: string;
};

export const catalogProducts: CatalogProduct[] = [
  {
    slug: "logitech-g-pro-x-superlight-2",
    name: "Logitech G Pro X Superlight 2",
    category: "Mice",
    type: "Wireless",
    tag: "Best Seller",
    price: "$159",
    description: "Tournament-favorite ultra-light wireless mouse with Hero 2 sensor and long battery life.",
    meter: "95%",
    specs: ["60g ultra-light", "Hero 2 sensor", "LIGHTSPEED wireless", "USB-C charging"],
    image: "/Mouse/Logitech G Pro X Superlight 2.webp",
  },
  {
    slug: "razer-viper-v3-pro",
    name: "Razer Viper V3 Pro",
    category: "Mice",
    type: "Esports",
    tag: "New",
    price: "$159",
    description: "Pro-grade symmetrical mouse with Focus Pro sensor and ultra-low click latency.",
    meter: "92%",
    specs: ["54g lightweight", "Focus Pro 35K sensor", "Gen-3 optical switches", "Up to 95h battery"],
    image: "/Mouse/Razer Viper V3 Pro.webp",
  },
  {
    slug: "logitech-g305-lightspeed",
    name: "Logitech G305 LIGHTSPEED",
    category: "Mice",
    type: "Budget Wireless",
    tag: "Value Pick",
    price: "$49",
    description: "Reliable low-latency wireless mouse that remains one of the most popular budget picks.",
    meter: "88%",
    specs: ["Hero sensor", "LIGHTSPEED wireless", "250h battery life", "Lightweight shell"],
    image: "/Mouse/Logitech G305 LIGHTSPEED.webp",
  },
  {
    slug: "wooting-60he",
    name: "Wooting 60HE+",
    category: "Keyboards",
    type: "60%",
    tag: "Esports Favorite",
    price: "$174",
    description: "Hall-effect rapid-trigger keyboard known for top-tier competitive gaming performance.",
    meter: "94%",
    specs: ["Rapid Trigger", "Lekker switches", "60% compact layout", "Per-key actuation control"],
    image: "/keyboard/Wooting 60HE+.jpg",
  },
  {
    slug: "steelseries-apex-pro-tkl-2023",
    name: "SteelSeries Apex Pro TKL (2023)",
    category: "Keyboards",
    type: "TKL",
    tag: "Tournament",
    price: "$189",
    description: "Premium TKL board with adjustable actuation for gaming and typing profiles.",
    meter: "90%",
    specs: ["OmniPoint 2.0", "Adjustable actuation", "TKL footprint", "OLED smart display"],
    image: "/keyboard/SteelSeries Apex Pro TKL (2023).jpg",
  },
  {
    slug: "keychron-k2-pro",
    name: "Keychron K2 Pro",
    category: "Keyboards",
    type: "75%",
    tag: "Work + Play",
    price: "$99",
    description: "Popular compact mechanical keyboard with hot-swap support and multi-device wireless.",
    meter: "86%",
    specs: ["75% layout", "Hot-swappable", "Bluetooth + wired", "QMK/VIA support"],
    image: "/keyboard/Keychron K2 Pro.jpg",
  },
  {
    slug: "hyperx-cloud-iii",
    name: "HyperX Cloud III",
    category: "Audio",
    type: "Headset",
    tag: "Best Seller",
    price: "$64",
    description: "Comfort-first wired gaming headset with strong mic clarity and broad platform support.",
    meter: "91%",
    specs: ["53mm drivers", "Detachable mic", "DTS spatial audio", "USB + 3.5mm"],
    image: "/headset/Hyperx Cloud III.jpg",
  },
  {
    slug: "logitech-g435-lightspeed",
    name: "Logitech G435 LIGHTSPEED",
    category: "Audio",
    type: "Wireless Headset",
    tag: "Lightweight",
    price: "$39",
    description: "Ultra-light wireless headset with Bluetooth plus LIGHTSPEED for desk and mobile use.",
    meter: "87%",
    specs: ["165g lightweight", "LIGHTSPEED + Bluetooth", "Dual beamforming mics", "18h battery"],
    image: "/headset/Logitech G435 LIGHTSPEED.jpg",
  },
  {
    slug: "razer-blackshark-v2-x",
    name: "Razer BlackShark V2 X",
    category: "Audio",
    type: "Headset",
    tag: "Value Pick",
    price: "$39",
    description: "Affordable wired headset with clear voice pickup and virtual 7.1 for PC players.",
    meter: "85%",
    specs: ["50mm drivers", "HyperClear cardioid mic", "Lightweight frame", "3.5mm jack"],
    image: "/headset/Razer BlackShark V2 X.jpg",
  },
  {
    slug: "anker-5-in-1-usb-c-hub",
    name: "Anker 5-in-1 USB-C Hub",
    category: "Power + Docks",
    type: "Hub",
    tag: "Creator Pick",
    price: "$19",
    description: "High-volume everyday USB-C hub pick for laptop users needing display and data ports.",
    meter: "90%",
    specs: ["4K HDMI", "2x USB-A data", "USB-C data", "Compact aluminum body"],
    image: "/power-Docks/Anker 5-in-1 USB-C Hub.jpg",
  },
  {
    slug: "ugreen-revodok-105-5-in-1-usb-c-hub",
    name: "UGREEN Revodok 105 5-in-1 USB-C Hub",
    category: "Power + Docks",
    type: "Hub",
    tag: "Top Rated",
    price: "$12",
    description: "Budget-friendly multiport hub with reliable HDMI output and power delivery pass-through.",
    meter: "89%",
    specs: ["4K HDMI", "100W PD pass-through", "3x USB-A", "Travel-ready size"],
    image: "/power-Docks/UGREEN Revodok 105 5-in-1 USB-C Hub.jpg",
  },
  {
    slug: "anker-735-ganprime-65w-charger",
    name: "Anker 735 GaNPrime 65W Charger",
    category: "Power + Docks",
    type: "Wall Charger",
    tag: "GaN",
    price: "$56",
    description: "Compact triple-port GaN charger that can handle laptop, phone, and accessories together.",
    meter: "88%",
    specs: ["65W total output", "2x USB-C + 1x USB-A", "GaN efficiency", "Foldable plug"],
    image: "/power-Docks/Anker 735 GaNPrime 65W Charger.jpg",
  },
  {
    slug: "logitech-g840-xl-gaming-mousepad",
    name: "Logitech G840 XL Gaming Mousepad",
    category: "Mousepads",
    type: "Control",
    tag: "Desk Mat",
    price: "$44",
    description: "Full-desk cloth mousepad with consistent glide and plenty of room for low-DPI aim.",
    meter: "84%",
    specs: ["900 x 400 mm", "Performance cloth", "Rubber base", "Desk-wide coverage"],
    image: "/mousepad/Logitech G840 XL Gaming Mousepad.jpg",
  },
  {
    slug: "steelseries-qck-heavy-xxl",
    name: "SteelSeries QcK Heavy XXL",
    category: "Mousepads",
    type: "Speed",
    tag: "Esports",
    price: "$39",
    description: "High-density micro-woven surface with extra thickness for stable flick and tracking control.",
    meter: "83%",
    specs: ["900 x 400 mm", "4mm thickness", "Micro-woven cloth", "Non-slip base"],
    image: "/mousepad/SteelSeries QcK Heavy XXL.jpg",
  },
  {
    slug: "logitech-c922-pro-stream-webcam",
    name: "Logitech C922 Pro Stream Webcam",
    category: "Streaming",
    type: "Webcam",
    tag: "Streaming",
    price: "$99",
    description: "Trusted streaming webcam with dependable autofocus and low-light correction.",
    meter: "87%",
    specs: ["1080p/30 or 720p/60", "Auto light correction", "Dual mics", "Tripod-ready mount"],
    image: "/streaming/Logitech C922 Pro Stream Webcam.jpg",
  },
  {
    slug: "elgato-key-light-air",
    name: "Elgato Key Light Air",
    category: "Streaming",
    type: "Lighting",
    tag: "Studio",
    price: "$129",
    description: "Creator-grade panel light with adjustable warmth and app control for cleaner camera shots.",
    meter: "86%",
    specs: ["1400 lumens", "2900K-7000K", "Wi-Fi app control", "Adjustable stand"],
    image: "/streaming/Elgato Key Light Air.png",
  },
  {
    slug: "baseus-blade-20000mah-65w-power-bank",
    name: "Baseus Blade 20000mAh 65W Power Bank",
    category: "Power + Docks",
    type: "Power Bank",
    tag: "Fast Charge",
    price: "$69",
    description: "High-capacity USB-C power bank for laptop and mobile charging on the go.",
    meter: "85%",
    specs: ["20,000mAh", "65W USB-C PD", "Slim design", "Digital power display"],
    image: "/power-Docks/Baseus Blade 20000mAh 65W Power Bank.jpg",
  },
  {
    slug: "fifine-am8-dynamic-microphone",
    name: "FIFINE AM8 Dynamic Microphone",
    category: "Audio",
    type: "Microphone",
    tag: "Creator",
    price: "$52",
    description: "Solid starter dynamic mic with both USB and XLR for stream and podcast upgrades.",
    meter: "84%",
    specs: ["USB + XLR", "Tap mute", "Gain knob", "RGB controllable"],
    image: "/streaming/FIFINE AM8 Dynamic Microphone.jpg",
  },
];

export const getProductBySlug = (slug: string) => {
  return catalogProducts.find((item) => item.slug === slug);
};
